Authorization
Michaeljogoh/Twitter-Clone pull request #4
Opened 2022-07-06 15:00 UTC by Michaeljogoh

Authorization using jwt

2022-07-07 11:01 UTC, Asylcreek requested changes

2022-07-07 11:01 UTC, Asylcreek commented on app.js
> +const {MongoURI}  = require('./config/key');
Is this import being used?

2022-07-07 11:01 UTC, Asylcreek commented on controllers/authController.js
> +        res.status(422).json({error:"Please fill in all field"})
Why `422`?

2022-07-07 11:01 UTC, Asylcreek commented on controllers/authController.js
> +        res.status(422).json({error:"password does not match"})
Why `422`?

2022-07-07 11:01 UTC, Asylcreek commented on controllers/authController.js
> +      if(user){
Please read up on how to use `async-await`

2022-07-07 11:01 UTC, Asylcreek commented on controllers/authController.js
> +    if(!name , !email , !username , !password, !password2 ){
This is defs not gonna give you what you expect.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

if `name, email, username, or password` are falsy and `password2` is truthy, the `if` block would be executed

2022-07-07 11:01 UTC, Asylcreek commented on controllers/authController.js
> +       res.status(422).json({error:"password must not be less than six characters"})
Why `422`?

2022-07-07 11:01 UTC, Asylcreek commented on controllers/authController.js
> +    })
Please use the async-await pattern

2022-07-07 11:01 UTC, Asylcreek commented on controllers/authController.js
> +        res.json(422).json({error:'Incorrect Password!!!'})
Your error message has `Incorrect password`
How is the password incorrect when you are checking if your user passed in their username/password?

2022-07-07 11:01 UTC, Asylcreek commented on controllers/authController.js
> +                return res.status(422).json({error:"Invalid email or  password"})
Please read up on the `async-await` pattern and use it here

2022-07-07 11:01 UTC, Asylcreek commented on middeware/authorization.js
> +        })
Please use the `async-await` pattern here

2022-07-13 11:14 UTC, merged

2022-07-13 11:18 UTC, Michaeljogoh commented on app.js
> +const {MongoURI}  = require('./config/key');
Yes

2022-07-13 11:20 UTC, Michaeljogoh commented on controllers/authController.js
> +        res.status(422).json({error:"Please fill in all field"})
I used it because the sever understands the content-type , but could not process it.

2022-07-13 11:21 UTC, Michaeljogoh commented on controllers/authController.js
> +      if(user){
I have changed it , sir

2022-07-13 11:22 UTC, Michaeljogoh commented on controllers/authController.js
> +        res.json(422).json({error:'Incorrect Password!!!'})
There is another error message for user

2022-07-13 11:22 UTC, Michaeljogoh commented on controllers/authController.js
> +                return res.status(422).json({error:"Invalid email or  password"})
ok sir

2022-07-13 11:23 UTC, Michaeljogoh commented on middeware/authorization.js
> +        })
ok sir

2022-07-13 11:24 UTC, Asylcreek commented on controllers/authController.js
> +        res.status(422).json({error:"Please fill in all field"})
But it's a Bad Request, because values do not match what the server expects it to be